### ISSUE TITLE
Discord 链接无效

### ISSUE THREAD

**Issue by merrkry** [BDFFZI/BDFFZI.github.io#1]
发现-相关链接-社区里的 Discord 链接不是邀请链接，无法用来加入频道。

这是 Custom Maid Server 的邀请链接：<https://discord.gg/custommaid>

---

倒狗横行的年代还能有这么清晰的指路帖，感动。

赞美站长！

**Comment by BDFFZI** [comment]
我居然现在才看到这个issues，不过已经改好了，当时那个发邮件的就是你吧，感谢。
