### ISSUE TITLE
关于汉化插件V4的问题和建议

### ISSUE THREAD

**Issue by JunweiSUN** [BDFFZI/BDFFZI.github.io#2]
Hi, 首先感谢指路站~有以下几个问题请教：
(1) 站中给出的V4原插件是 COM3D2.i18nEx，但发现你只fork了 CM3D2.YATranslator 这个repo，这个repo原来的场景是CM3D2，fork后改名成了COM3D2。想问一下之后V4的开发会基于新的 COM3D2.i18nEx 还是 CM3D2.YATranslator
(2) 新式翻译插件指的是例如调chatgpt得到的翻译结果吗？
(3) 我也是.Net开发者，如果可以的话我也可以参与到开发工作中 :-)

**Comment by BDFFZI** [comment]
### 关于CM3D2.YATranslator的改名：
1. 因为我只在COM3D2中进行了测试，所以将CM3D2改成了COM3D2。
2. 另外其实以前就有一款叫COM3D2.YATranslator的插件，功能上和我这个类似，但它是不开源的，所以我这个也有平替的意思在内。
3. 所以本质上这个插件并未没有太多改动，因此在CM3D2中应该也是可以使用的。

### 关于V4开发的插件选择：
1. V4的开发会基于COM3D2.i18nEx，这个插件接入了官方翻译功能，在处理图片翻译上优势很大（似乎是将很多界面的按钮转换成了文本进行翻译），而且似乎可以和XUnity.AutoTranslator兼容。
2. 但CM3D2.YATranslator就不具有以上优势，游戏里要翻译的图片实际上是程序自动生成的图集，这就导致不同版本的图片位置很可能不同，所以这种翻译会限制游戏版本。

### V4是否会使用类似Chatgpt的翻译结果：
1. 是的，v4的一大特色就是会采用高质量的新式AI翻译。目前国内已经有人这么干了，但看样子作者只会在小圈子里发布，所以我们需要自己准备汉化文件。
2. 我是想乘此机会学习一下人工智能相关的知识，然后自己去训练一个中日翻译的模型。目前很多游戏都有成熟的翻译工具，唯一缺的就是翻译文件，若能把这个模型做出来，那对任何游戏翻译都有极大的帮助。
3. 其实中日翻译模型也同样有人做了，据说是拿日本轻小说的中日译文做的训练，效果比传统机翻好的多也更适合日文游戏翻译，不过同样也都是不开源的东西。

### 关于V4的开发工作：
我对v4的开发其实也不过是个随缘的态度，目前v4汉化开发的启动时间我是放在了2024年下半年，因为上半年我要处理找工作的事，如果工作稳定了，v4汉化的开发才会真正开始。

目前v4开发需要完成以下三个任务：
1. 确认COM3D2.i18nEx的可用性，优化或修复里面的一些bug。
2. 训练一个高质量的中日翻译模型。（可选）
3. 准备一份来自新式AI的高质量翻译文件。

#### 关于合作开发
我没有多少合作开发的经验，而且上面的任务感觉不太适合进一步细分，不过如果你有兴趣，欢迎发布pull requests，或者如果你先进行了开发，我也不介意fork，谢谢支持😉

**Comment by JunweiSUN** [comment]
Hi @BDFFZI 感谢回复
对于翻译模型，我的观点是直接调gpt之类的大模型api，辅以必要的prompt可能会比直接用在中日语料上面训练的小模型效果会更好，因为毕竟gpt的语料库要大得多。我接下来会抽点时间验证这一点。我研究生期间也是做深度学习相关，如果你需要训练模型缺少算力的话可以使用我的N卡~
我会先大概COM3D2.i18nEx的code，了解一下框架，祝找工作顺利，keep in touch~

**Comment by BDFFZI** [comment]
你说的没错，所以我把这项任务标记为了可选，不过我是白嫖怪，所以也不想花钱调用api了，不过那位现在在搞gpt翻译的大佬未来也是有可能彻底公开翻译文件的。我只是个业余人士，这方面你们比我厉害的多，期待未来了👍
